from bs4 import BeautifulSoup
import urllib.request
import requests
import psycopg2

### DB 연결
conn = psycopg2.connect(host='localhost',
                        dbname='groupproject',
                        user='postgres',
                        password='******',
                        port='5432')
conn.autocommit = True
cur = conn.cursor()

### OPEN API 연결
API_URL = 'http://apis.data.go.kr/9760000/WinnerInfoInqireService2/getWinnerInfoInqire' #당선자 정보
#API_URL = 'http://apis.data.go.kr/9760000/ElecPrmsInfoInqireService/getCnddtElecPrmsInfoInqire' #선거공약 정보
API_KEY = "*************************************************************************"
apiload = {"pageNo": "1", "numOfRows": "250", "sgId": "20180613", "sgTypecode": "3", 
           "serviceKey": requests.utils.unquote(API_KEY)}
headers = {
    'User-Agent': "PostmanRuntime/7.17.1",
    'Accept': "*/*",
    'Cache-Control': "no-cache",
    'Postman-Token': "95c151d9-9676-4069-a9b5-9bbd72bf5319,cd4efab7-c0c4-4714-a2a3-2a6e03677233",
    'Host': "openapi.molit.go.kr:8081",
    'Accept-Encoding': "gzip, deflate",
    'Cookie': "ROUTEID=.HTTP1",
    'Connection': "keep-alive",
    'cache-control': "no-cache"
}
response = requests.request("GET", API_URL, headers=headers, params=apiload)

### CREATE TABLE
cur.execute("CREATE TABLE appUser(userId INT, name VARCHAR(20), age VARCHAR(10), gender VARCHAR(2),region VARCHAR(30), PRIMARY KEY(userId));")

cur.execute("CREATE TABLE Elected(sgId INT, sgTypecode INT, huboId INT, sggName VARCHAR(50), sdName VARCHAR(40), wiwName VARCHAR(40), "
            "giho INT, jdName VARCHAR(50), name VARCHAR(50), hanjaName VARCHAR(50), gender VARCHAR(1), birthday INT, age INT, "
            "jobId INT, job VARCHAR(200), eduId INT, edu VARCHAR(200), career1 VARCHAR(200), career2 VARCHAR(200), dugsu INT, "
            "dugyul FLOAT, PRIMARY KEY(huboId));")

cur.execute("CREATE TABLE Pledge(sgId INT, sgTypeCode INT, krName VARCHAR(50), cnName VARCHAR(10), cnddtId INT, partyName VARCHAR(50), "
            "sggName VARCHAR(80), sidoName VARCHAR(40), wiwName VARCHAR(40), prmsTitle VARCHAR(255), prmmCont text, PRIMARY KEY(cnddtId));")

cur.execute("CREATE TABLE Vote(userId INT, huboId INT, primary key(userId, huboId), "
            "foreign key(userId) references appUser(userId), foreign key(huboId) references Elected(huboId));")

cur.execute("CREATE TABLE Mark(userId INT, huboId INT, primary key(userId, huboId), "
            "foreign key(userId) references appUser(userId), foreign key(huboId) references Elected(huboId));")

### CREATE TRIGGER
cur.execute("CREATE FUNCTION F1() returns trigger as $F1$ "
                    "BEGIN "
                    "delete from Vote where userId = OLD.userId;"
                    "RETURN NEW;"
                    "END;"
                    "$F1$LANGUAGE plpgsql;"
                    "CREATE TRIGGER R1 "
                    "AFTER DELETE ON appUser "
                    "FOR EACH ROW "
                    "EXECUTE PROCEDURE F1();")

cur.execute("CREATE FUNCTION F2() returns trigger as $F2$ "
                    "BEGIN "
                    "delete from Mark where userId = OLD.userId;"
                    "RETURN NEW;"
                    "END;"
                    "$F2$LANGUAGE plpgsql;"
                    "CREATE TRIGGER R2 "
                    "AFTER DELETE ON appUser "
                    "FOR EACH ROW "
                    "EXECUTE PROCEDURE F2();")

cur.execute("CREATE FUNCTION F3() returns trigger as $F3$ "
                    "BEGIN "
                    "IF ((SELECT count(*) from Vote where userId = NEW.userId)>5) THEN "
                    "RETURN NULL;"
                    "ELSE "
                    "RETURN NEW;"
                    "END IF;"
                    "END;"
                    "$F3$LANGUAGE plpgsql;"
                    "CREATE TRIGGER R3 "
                    "BEFORE INSERT ON Vote "
                    "FOR EACH ROW "
                    "EXECUTE PROCEDURE F3();")

cur.execute("CREATE FUNCTION F4() returns trigger as $F4$ "
                    "BEGIN "
                    "IF ((SELECT count(*) from Mark where userId = NEW.userId)>10) THEN "
                    "RETURN NULL;"
                    "ELSE "
                    "RETURN NEW;"
                    "END IF;"
                    "END;"
                    "$F4$LANGUAGE plpgsql;"
                    "CREATE TRIGGER R4 "
                    "BEFORE INSERT ON Mark "
                    "FOR EACH ROW "
                    "EXECUTE PROCEDURE F4();")

### INSERT TUPLE
#INSERT INTO APPUSER TABLE
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (100,"김수원","20대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (101,"김영통","20대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (102,"김팔달","20대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (103,"김장안","20대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (104,"김화성","20대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (105,"김아주","20대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (106,"김민철","20대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (107,"김윤환","20대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (108,"김경모","20대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (109,"김영호","20대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (110,"김제동","20대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (111,"김성은","20대","남","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (112,"김두열","20대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (113,"김현제","20대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (114,"김윤철","20대","여","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (115,"김진묵","20대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (116,"김학수","20대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (117,"김지호","20대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (118,"김상욱","20대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (119,"김태규","20대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (120,"김태민","20대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (121,"이영호","20대","여","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (122,"이예훈","30대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (123,"조기석","30대","남","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (124,"한두열","30대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (125,"전상욱","30대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (126,"이재호","30대","여","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (127,"유영진","30대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (128,"윤용태","30대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (129,"유진우","30대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (130,"박준오","30대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (131,"전태규","30대","남","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (132,"김택용","30대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (133,"박상현","30대","여","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (134,"임성춘","30대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (135,"이승원","30대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (136,"박상현","30대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (137,"김지성","30대","남","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (138,"이광용","30대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (139,"원지훈","30대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (140,"이성은","30대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (141,"장윤철","40대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (142,"김성대","40대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (143,"윤찬희","40대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (144,"황병영","40대","남","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (145,"김태영","40대","여","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (146,"박태민","40대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (147,"도재욱","40대","여","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (148,"최호선","40대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (149,"정영재","40대","여","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (150,"박재혁","40대","여","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (151,"김홍덕","40대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (152,"김명운","40대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (153,"변현제","40대","여","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (154,"김윤환","40대","남","충청북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (155,"임진묵","40대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (156,"정민기","40대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (157,"변형태","40대","남","충청북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (158,"조일장","40대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (159,"임홍규","40대","남","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (160,"구성훈","40대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (161,"윤수철","50대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (162,"이영웅","50대","여","충청북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (163,"송병구","50대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (164,"김민철","50대","남","충청북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (165,"김경모","50대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (166,"김학수","50대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (167,"서지훈","50대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (168,"임요환","50대","여","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (169,"홍진호","50대","남","충청북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (170,"윤용태","50대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (171,"김학수","50대","여","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (172,"구성훈","50대","남","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (173,"배병우","50대","여","강원도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (174,"김장육","50대","남","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (175,"강태완","50대","여","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (176,"박성진","50대","남","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (177,"원선재","50대","여","경상북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (178,"배성흠","50대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (179,"김병수","50대","남","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (180,"현지섭","50대","여","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (181,"박철순","50대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (182,"지동원","60대","남","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (183,"유승곤","60대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (184,"김광용","60대","남","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (185,"안경덕","60대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (186,"윤지환","60대","여","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (187,"윤진규","60대","여","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (188,"박희수","60대","남","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (189,"전병기","60대","여","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (190,"강민우","60대","남","충청남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (191,"한태성","60대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (192,"김준혁","60대","남","전라북도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (193,"지용희","60대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (194,"이상철","60대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (195,"윤민구","60대","여","경기도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (196,"김강석","60대","남","전라남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (197,"지동원","60대","남","경상남도",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (198,"김병수","60대","여","서울특별시",))
cur.execute("insert into appUser (userId, name, age, gender, region) values (%s, %s, %s, %s, %s)", (199,"김범수","60대","여","서울특별시",))

#INSERT INTO ELECTED TABLE
with urllib.request.urlopen(response.url) as response:
    html = response.read()
    soup = BeautifulSoup(html, 'html.parser')
    data = soup.find_all("item")

for elected in data:
    sgId = elected.find('sgid')
    sgTypecode = elected.find('sgtypecode')
    huboId = elected.find('huboid')
    sggName = elected.find('sggname')
    sdName = elected.find('sdname')
    wiwName = elected.find('wiwname')
    giho = elected.find('giho')
    jdName = elected.find('jdname')
    name = elected.find('name')
    hanjaName = elected.find('hanjaname')
    gender = elected.find('gender')
    birthday = elected.find('birthday')
    age = elected.find('age')
    jobId = elected.find('jobid')
    job = elected.find('job')
    eduId = elected.find('eduid')
    edu = elected.find('edu')
    career1 = elected.find('career1')
    career2 = elected.find('career2')
    dugsu = elected.find('dugsu')
    dugyul = elected.find('dugyul')
    cur.execute("insert into Elected (sgId, sgTypecode, huboId, sggName, sdName, wiwName, giho, jdName, name, hanjaName, gender, birthday, age, jobId, job, eduId, edu, career1, career2, dugsu, dugyul) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (sgId.get_text(), sgTypecode.get_text(), huboId.get_text(), sggName.get_text(), sdName.get_text(), wiwName.get_text(), giho.get_text(), jdName.get_text(), name.get_text(), hanjaName.get_text(), gender.get_text(), birthday.get_text(), age.get_text(), jobId.get_text(), job.get_text(), eduId.get_text(), edu.get_text(), career1.get_text(), career2.get_text(), dugsu.get_text(), dugyul.get_text(),))

apiload["sgTypecode"] = 4
response = requests.request("GET", API_URL, headers=headers, params=apiload)

with urllib.request.urlopen(response.url) as response:
    html = response.read()
    soup = BeautifulSoup(html, 'html.parser')
    data = soup.find_all("item")

for elected in data:
    sgId = elected.find('sgid')
    sgTypecode = elected.find('sgtypecode')
    huboId = elected.find('huboid')
    sggName = elected.find('sggname')
    sdName = elected.find('sdname')
    wiwName = elected.find('wiwname')
    giho = elected.find('giho')
    jdName = elected.find('jdname')
    name = elected.find('name')
    hanjaName = elected.find('hanjaname')
    gender = elected.find('gender')
    birthday = elected.find('birthday')
    age = elected.find('age')
    jobId = elected.find('jobid')
    job = elected.find('job')
    eduId = elected.find('eduid')
    edu = elected.find('edu')
    career1 = elected.find('career1')
    career2 = elected.find('career2')
    dugsu = elected.find('dugsu')
    dugyul = elected.find('dugyul')
    cur.execute("insert into Elected (sgId, sgTypecode, huboId, sggName, sdName, wiwName, giho, jdName, name, hanjaName, gender, birthday, age, jobId, job, eduId, edu, career1, career2, dugsu, dugyul) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (sgId.get_text(), sgTypecode.get_text(), huboId.get_text(), sggName.get_text(), sdName.get_text(), wiwName.get_text(), giho.get_text(), jdName.get_text(), name.get_text(), hanjaName.get_text(), gender.get_text(), birthday.get_text(), age.get_text(), jobId.get_text(), job.get_text(), eduId.get_text(), edu.get_text(), career1.get_text(), career2.get_text(), dugsu.get_text(), dugyul.get_text(),))

#INSERT INTO PLEDGE TABLE
for elected in data:
    API_URL = 'http://apis.data.go.kr/9760000/ElecPrmsInfoInqireService/getCnddtElecPrmsInfoInqire' #선거공약 정보
    huboId = elected.find('huboid')
    apiload["cnddtId"] = huboId.get_text()
    response = requests.request("GET", API_URL, headers=headers, params=apiload)
    with urllib.request.urlopen(response.url) as response:
        html = response.read()
        soup = BeautifulSoup(html, 'html.parser')
        pData = soup.find_all("item")
    for pledge in pData:
        sgId = pledge.find('sgid')
        sgTypecode = pledge.find('sgtypecode')
        cnddtId = pledge.find('cnddtid')
        sggName = pledge.find('sggname')
        sidoName = pledge.find('sidoname')
        wiwName = pledge.find('wiwname')
        partyName = pledge.find('partyname')
        krName = pledge.find('krname')
        cnName = pledge.find('cnname')
        prmsTitle = pledge.find('prmstitle1')
        prmmCont = pledge.find('prmmcont1')
        cur.execute("insert into Pledge (sgId, sgTypecode, cnddtId, sggName, sidoName, wiwName, "
                "partyName, krName, cnName, prmsTitle, prmmCont) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                (sgId.get_text(), sgTypecode.get_text(), cnddtId.get_text(), sggName.get_text(), sidoName.get_text(), wiwName.get_text(), partyName.get_text(), krName.get_text(), cnName.get_text(), prmsTitle.get_text(), prmmCont.get_text(),))

del(apiload['cnddtId'])
apiload["sgTypecode"] = 3
API_URL = 'http://apis.data.go.kr/9760000/WinnerInfoInqireService2/getWinnerInfoInqire'#당선자 정보
response = requests.request("GET", API_URL, headers=headers, params=apiload)

with urllib.request.urlopen(response.url) as response:
    html = response.read()
    soup = BeautifulSoup(html, 'html.parser')
    data = soup.find_all("item")

for elected in data:
    API_URL = 'http://apis.data.go.kr/9760000/ElecPrmsInfoInqireService/getCnddtElecPrmsInfoInqire'#선거공약 정보
    huboId = elected.find('huboid')
    apiload["cnddtId"] = huboId.get_text()
    response = requests.request("GET", API_URL, headers=headers, params=apiload)
    with urllib.request.urlopen(response.url) as response:
        html = response.read()
        soup = BeautifulSoup(html, 'html.parser')
        pData = soup.find_all("item")
    for pledge in pData:
        sgId = pledge.find('sgid')
        sgTypecode = pledge.find('sgtypecode')
        cnddtId = pledge.find('cnddtid')
        sggName = pledge.find('sggname')
        sidoName = pledge.find('sidoname')
        wiwName = pledge.find('wiwname')
        partyName = pledge.find('partyname')
        krName = pledge.find('krname')
        cnName = pledge.find('cnname')
        prmsTitle = pledge.find('prmstitle1')
        prmmCont = pledge.find('prmmcont1')
        cur.execute("insert into Pledge (sgId, sgTypecode, cnddtId, sggName, sidoName, wiwName, "
                "partyName, krName, cnName, prmsTitle, prmmCont) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                (sgId.get_text(), sgTypecode.get_text(), cnddtId.get_text(), sggName.get_text(), sidoName.get_text(), wiwName.get_text(), partyName.get_text(), krName.get_text(), cnName.get_text(), prmsTitle.get_text(), prmmCont.get_text(),))

#INSERT INTO VOTE TABLE
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (100, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (101, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (102, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (105, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (106, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (110, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (122, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (123, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (129, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (120, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (121, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (132, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (135, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (146, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (140, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (142, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (143, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (149, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (150, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (151, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (152, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (155, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (156, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (160, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (172, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (173, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (179, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (180, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (181, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (182, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (185, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (196, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (190, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (192, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (193, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (199, 100121126,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (103, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (104, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (105, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (106, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (107, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (108, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (109, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (123, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (124, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (135, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (136, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (147, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (148, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (149, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (153, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (154, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (155, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (166, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (167, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (168, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (179, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (113, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (114, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (115, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (116, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (117, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (118, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (119, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (173, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (174, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (175, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (176, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (177, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (188, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (189, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (180, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (181, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (182, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (183, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (184, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (192, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (190, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (191, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (194, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (195, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (196, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (198, 100123380,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (100, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (101, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (102, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (103, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (104, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (105, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (106, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (107, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (108, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (109, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (110, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (113, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (115, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (118, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (120, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (123, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (125, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (128, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (130, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (133, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (135, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (138, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (140, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (143, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (145, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (148, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (150, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (153, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (155, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (158, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (160, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (163, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (165, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (168, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (170, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (173, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (175, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (178, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (180, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (183, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (185, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (188, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (190, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (193, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (195, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (198, 100125818,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (101, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (102, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (104, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (105, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (107, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (109, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (111, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (112, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (114, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (115, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (117, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (119, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (121, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (122, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (124, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (125, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (127, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (129, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (131, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (132, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (134, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (135, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (137, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (139, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (141, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (142, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (144, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (145, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (147, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (149, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (151, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (152, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (154, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (155, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (157, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (159, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (161, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (162, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (164, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (165, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (167, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (169, 100131769,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (130, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (140, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (150, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (160, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (170, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (180, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (190, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (110, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (120, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (123, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (134, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (145, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (156, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (167, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (178, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (189, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (198, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (187, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (176, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (165, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (154, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (143, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (132, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (121, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (136, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (147, 100122673,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (124, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (135, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (146, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (157, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (168, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (179, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (180, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (197, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (186, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (175, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (164, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (153, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (142, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (131, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (114, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (125, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (136, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (147, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (158, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (169, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (115, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (126, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (137, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (148, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (159, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (195, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (184, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (173, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (162, 100131885,))
cur.execute("insert into Vote (userId, huboId) values (%s, %s)", (151, 100131885,))

#INSERT INTO MARK TABLE
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (100, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (101, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (102, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (105, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (106, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (110, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (122, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (123, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (129, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (120, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (121, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (132, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (135, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (146, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (140, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (142, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (143, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (149, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (150, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (151, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (152, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (155, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (156, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (160, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (172, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (173, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (179, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (180, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (181, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (182, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (185, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (196, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (190, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (192, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (193, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (199, 100121126,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (103, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (104, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (105, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (106, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (107, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (108, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (109, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (123, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (124, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (135, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (136, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (147, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (148, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (149, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (153, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (154, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (155, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (166, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (167, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (168, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (179, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (113, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (114, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (115, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (116, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (117, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (118, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (119, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (173, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (174, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (175, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (176, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (177, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (188, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (189, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (180, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (181, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (182, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (183, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (184, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (192, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (190, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (191, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (194, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (195, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (196, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (198, 100123380,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (100, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (101, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (102, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (103, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (104, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (105, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (106, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (107, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (108, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (109, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (110, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (113, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (115, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (118, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (120, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (123, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (125, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (128, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (130, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (133, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (135, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (138, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (140, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (143, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (145, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (148, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (150, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (153, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (155, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (158, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (160, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (163, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (165, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (168, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (170, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (173, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (175, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (178, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (180, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (183, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (185, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (188, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (190, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (193, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (195, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (198, 100125818,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (101, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (102, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (104, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (105, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (107, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (109, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (111, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (112, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (114, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (115, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (117, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (119, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (121, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (122, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (124, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (125, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (127, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (129, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (131, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (132, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (134, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (135, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (137, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (139, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (141, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (142, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (144, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (145, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (147, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (149, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (151, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (152, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (154, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (155, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (157, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (159, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (161, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (162, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (164, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (165, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (167, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (169, 100131769,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (130, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (140, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (150, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (160, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (170, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (180, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (190, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (110, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (120, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (123, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (134, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (145, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (156, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (167, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (178, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (189, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (198, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (187, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (176, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (165, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (154, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (143, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (132, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (121, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (136, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (147, 100122673,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (124, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (135, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (146, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (157, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (168, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (179, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (180, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (197, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (186, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (175, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (164, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (153, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (142, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (131, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (114, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (125, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (136, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (147, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (158, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (169, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (115, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (126, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (137, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (148, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (159, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (195, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (184, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (173, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (162, 100131885,))
cur.execute("insert into Mark (userId, huboId) values (%s, %s)", (151, 100131885,))